In [1]:
import csv as csv 
import numpy as np

# Open up the csv file in to a Python object
csv_file_object = csv.reader(open('../MachineLearning/train.csv', 'rb')) 
header = csv_file_object.next()  # The next() command just skips the 
                                 # first line which is a header
data=[]                          # Create a variable called 'data'.
for row in csv_file_object:      # Run through each row in the csv file,
    data.append(row)             # adding each row to the data variable
data = np.array(data)            # Then convert from a list to an array
			         # Be aware that each item is currently
                                 # a string in this format

In [2]:
number_passengers = np.size(data[0::,1].astype(np.float))
number_survived = np.sum(data[0::,1].astype(np.float))
proportion_survivors = number_survived / number_passengers
women_only_stats = data[0::,4] == "female" # This finds where all 
                                           # the elements in the gender
                                           # column that equals “female”
men_only_stats = data[0::,4] != "female"   # This finds where all the 
                                           # elements do not equal 
                                           # female (i.e. male)
women_onboard = data[women_only_stats,1].astype(np.float)     
men_onboard = data[men_only_stats,1].astype(np.float)

# Then we finds the proportions of them that survived
proportion_women_survived = \
                       np.sum(women_onboard) / np.size(women_onboard)  
proportion_men_survived = \
                       np.sum(men_onboard) / np.size(men_onboard) 

# and then print it out
print 'Proportion of women who survived is %s' % proportion_women_survived
print 'Proportion of men who survived is %s' % proportion_men_survived

Proportion of women who survived is 0.742038216561
Proportion of men who survived is 0.188908145581


In [3]:
fare_ceiling = 40
data[data[0::,9].astype(np.float) >= fare_ceiling, 9] = fare_ceiling -1.0


In [4]:
print data[0::,9]

['7.25' '39.0' '7.925' '39.0' '8.05' '8.4583' '39.0' '21.075' '11.1333'
 '30.0708' '16.7' '26.55' '8.05' '31.275' '7.8542' '16' '29.125' '13' '18'
 '7.225' '26' '13' '8.0292' '35.5' '21.075' '31.3875' '7.225' '39.0'
 '7.8792' '7.8958' '27.7208' '39.0' '7.75' '10.5' '39.0' '39.0' '7.2292'
 '8.05' '18' '11.2417' '9.475' '21' '7.8958' '39.0' '7.8792' '8.05' '15.5'
 '7.75' '21.6792' '17.8' '39.6875' '7.8' '39.0' '26' '39.0' '35.5' '10.5'
 '7.2292' '27.75' '39.0' '7.2292' '39.0' '39.0' '27.9' '27.7208' '15.2458'
 '10.5' '8.1583' '7.925' '8.6625' '10.5' '39.0' '39.0' '14.4542' '39.0'
 '7.65' '7.8958' '8.05' '29' '12.475' '9' '9.5' '7.7875' '39.0' '10.5'
 '15.85' '34.375' '8.05' '39.0' '8.05' '8.05' '7.8542' '39.0' '20.575'
 '7.25' '8.05' '34.6542' '39.0' '23' '26' '7.8958' '7.8958' '39.0' '8.6542'
 '7.925' '7.8958' '7.65' '7.775' '7.8958' '24.15' '39.0' '14.4542' '8.05'
 '9.825' '14.4583' '7.925' '7.75' '21' '39.0' '31.275' '39.0' '8.05'
 '30.0708' '13' '39.0' '11.2417' '7.75' '7.1417' '22.3

In [6]:
fare_bracket_size = 10
number_of_price_brackets = fare_ceiling/fare_bracket_size
#number_of_classes upper,lower etc = 3
number_of_classes = len(np.unique(data[0::,2]))
survival = np.zeros((2,number_of_classes,number_of_price_brackets))

In [8]:
for i in xrange(number_of_classes):
    for j in xrange(number_of_price_brackets):
        women_only_stats = data[
                            (data[0::,4] == "female")\
                           &(data[0::,2].astype(np.float)==i+1)\
                           &(data[0:,9].astype(np.float) >= j*fare_bracket_size)\
                           &(data[0:,9].astype(np.float) <(j+1)*fare_bracket_size),1]
        men_only_stats = data[
                            (data[0::,4] !="female")\
                           &(data[0::,2].astype(np.float) == i+1)\
                           &(data[0:,9].astype(np.float) >= j*fare_bracket_size)\
                           &(data[0:,9].astype(np.float) < (j+1)*fare_bracket_size),1]     ]

In [11]:
print women_only_stats
print men_only_stats

['1' '0' '0' '0' '0' '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
[ True False False False  True  True  True  True False False False False
  True  True False False  True  True False False  True  True False  True
 False False  True  True False  True  True False False  True  True  True
  True  True False False False False  True False False  True  True False
  True False  True  True False False  True  True False  True False  True
  True False  True  True  True  True False  True False  True  True False
  True  True  True  True  True  True  True False  True  True False  True
 False False  True  True False  True  True  True  True  True  True  True
  True  True False  True False  True  True  True  True  True False  True
  True False  True False  True False False  True  True  True  True False
  True  True  True False  True  True  True  True False  True  True  True
 False False  True  True False  True  True  True False False False  True
  True  True  True False  True  True  True False  True  Tr

In [13]:
survival_table = np.zeros((2, number_of_classes, number_of_price_brackets))
survival_table[0,i,j] = np.mean(women_only_stats.astype(np.float)) 
survival_table[1,i,j] = np.mean(men_only_stats.astype(np.float))

In [14]:
survival_table[ survival_table < 0.5 ] = 0
survival_table[ survival_table >= 0.5 ] = 1

In [32]:
test_file = open('../MachineLearning/test.csv','rb')
test_file_object = csv.reader(test_file)
header = test_file_object.next()
prediction_file = open('../MachineLearning/genderClassModel.csv',"wb")
p = csv.writer(prediction_file)
p.writerow(["PassengerId","Survived"])

In [33]:
for row in test_file_object:                 # We are going to loop
                                              # through each passenger
                                              # in the test set                     
  for j in xrange(number_of_price_brackets):  # For each passenger we
                                              # loop thro each price bin
    try:                                      # Some passengers have no
                                              # Fare data so try to make
      row[8] = float(row[8])                  # a float
    except:                                   # If fails: no data, so 
      bin_fare = 3 - float(row[1])            # bin the fare according Pclass
      break                                   # Break from the loop
    if row[8] > fare_ceiling:              # If there is data see if
                                              # it is greater than fare
                                              # ceiling we set earlier
      bin_fare = number_of_price_brackets-1   # If so set to highest bin
      break                                   # And then break loop
    if row[8] >= j * fare_bracket_size\
       and row[8] < \
       (j+1) * fare_bracket_size:             # If passed these tests 
                                              # then loop through each bin 
      bin_fare = j                            # then assign index
      break                                   
    if row[3] == 'female':                             #If the passenger is female
        p.writerow([row[0], "%d" % \
                   int(survival_table[0, float(row[1])-1, bin_fare])])
    else:                                          #else if male
        p.writerow([row[0], "%d" % \
                   int(survival_table[1, float(row[1])-1, bin_fare])])
     
# Close out the files.
test_file.close() 
prediction_file.close()

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:22: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:24: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [34]:
print survival_table

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  1.]]]
